### ISSUE TITLE
Restore detekt GitHub workflow

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/tool-base#22]
The workflow was temporarily removed because of the issues in the tool occurred during working on PR #21. Briefly, the history of removing of the workflow is this.

At some stage the detekt workflow started failing with the following error:
```
Run github/codeql-action/upload-sarif@v1
Uploading results
  Processing sarif files: ["/home/runner/work/tool-base/tool-base/detekt.sarif.json"]
  Error: Unexpected end of JSON input
  SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at validateSarifFileSchema (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:191:24)
      at uploadFiles (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:268:9)
      at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:[14](https://github.com/SpineEventEngine/tool-base/runs/6097890868?check_suite_focus=true#step:7:14)0:[18](https://github.com/SpineEventEngine/tool-base/runs/6097890868?check_suite_focus=true#step:7:18))
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async run (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:51:30)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:69:9)
```

Trying to bump the version of detekt any further beyond `v1.15.0` (which was used in the original workflow script), results in the following error:

```
Run dest=$( mktemp -d )
  dest=$( mktemp -d )
  curl --request GET \
    --url null \
    --silent \
    --location \
    --output $dest/detekt
  chmod a+x $dest/detekt
  echo $dest >> $GITHUB_PATH
  shell: /usr/bin/bash -e {0}
  env:
    DETEKT_RELEASE_TAG: v1.16.0
Error: Process completed with exit code 6.
```

The error occurs because the following part of the script obtains `null` download URL:
```
      # Gets the download URL associated with the $DETEKT_RELEASE_TAG
      - name: Get Detekt download URL
        id: detekt_info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DETEKT_DOWNLOAD_URL=$( gh api graphql --field tagName=$DETEKT_RELEASE_TAG --raw-field query='
            query getReleaseAssetDownloadUrl($tagName: String!) {
              repository(name: "detekt", owner: "detekt") {
                release(tagName: $tagName) {
                  releaseAssets(name: "detekt", first: 1) {
                    nodes {
                      downloadUrl
                    }
                  }
                }
              }
            }
          ' | \
          jq --raw-output '.data.repository.release.releaseAssets.nodes[0].downloadUrl' )
          echo "::set-output name=download_url::$DETEKT_DOWNLOAD_URL"
```

Why this works for `DETEKT_RELEASE_TAG` set to `v1.15.0`, and does not for anything starting from `v1.16.0` is complete mystery to me.

Also it should be said that detekt workflow script available from GitHub Actions at the moment obtains the download URL differently:

```
# Gets the download URL associated with the $DETEKT_RELEASE_TAG
    - name: Get Detekt download URL
      id: detekt_info
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api graphql --field tagName=$DETEKT_RELEASE_TAG --raw-field query='
          query getReleaseAssetDownloadUrl($tagName: String!) {
            repository(name: "detekt", owner: "detekt") {
              release(tagName: $tagName) {
                releaseAssets(name: "detekt", first: 1) {
                  nodes {
                    downloadUrl
                  }
                }
                tagCommit {
                  oid
                }
              }
            }
          }
        ' 1> gh_response.json
        
        DETEKT_RELEASE_SHA=$(jq --raw-output '.data.repository.release.releaseAssets.tagCommit.oid' gh_response.json)
        if [ $DETEKT_RELEASE_SHA != "37f0a1d006977512f1f216506cd695039607c3e5" ]; then
          echo "Release tag doesn't match expected commit SHA"
          exit 1
        fi
        
        DETEKT_DOWNLOAD_URL=$(jq --raw-output '.data.repository.release.releaseAssets.nodes[0].downloadUrl' gh_response.json)
        echo "::set-output name=download_url::$DETEKT_DOWNLOAD_URL"
```
As you can see it now checks for commit SHA (which should correspond to the commit behind the tag). Trying to use this version of workflow script brings no luck because the returned URL is `null`.

Further steps for approaching this issue would be:

1. Try to perform `gh api` calls locally to see if the structure of the returned query result matches what the script expects.
2. Wait until the latest version of detekt (v1.20.0) gets some adoption with the hope that the issues we're experiencing are resolved.

**Comment by alexander-yevsyukov** [comment]
Found an [alternative workflow](https://blog.coffeebeans.at/archives/1826) for running detekt via GitHub Actions. It's dated March 15, 2022, and uses v1.19.0. The post also tells that the standard script didn't work for the author either.

The script should be adjusted to use Java 11 instead of 17.

**Comment by alexander-yevsyukov** [comment]
An alternative found in this [detekt discussion](https://github.com/detekt/detekt/discussions/3369):

https://github.com/marketplace/actions/setup-detekt

It's a GitHub Action which installs specified version of detekt.

**Comment by yevhenii-nadtochii** [comment]
This issue isn't actual anymore. The mentioned workflow has been [dropped](https://github.com/SpineEventEngine/tool-base/pull/35) due to [config #412](https://github.com/SpineEventEngine/config/issues/412).

I'm closing this issue.
